version: "3.3"
services:
  server:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: tsed-mongo-sdk/server:latest
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true

  mongodb:
    image: mongo:4.4
    ports:
      - "27017:27017"
